import { injectable } from "tsyringe";
import axios from "axios";
import logger from "../config/logger";

const VOICENSMS_BASE_URL_SMS = process.env.VOICENSMS_BASE_URL_SMS || "https://api.voicensms.in/SMSAPI/webresources/CreateSMSCampaignPost";
const VOICENSMS_BASE_URL_CALL = process.env.VOICENSMS_BASE_URL_CALL || "https://api.voicensms.in/SMSAPI/webresources/CreateOBDCampaignPost";
const VOICENSMS_AUTHKEY = process.env.VOICENSMS_AUTHKEY || "HKljQWxZTHOUbpRmyXt2wcVQh";
const VOICENSMS_VOICE_SERVICE_NO = process.env.VOICENSMS_VOICE_SERVICE_NO || "7317155498";

@injectable()
export class SMSService {

    otpMessage = "Dear <arg1>, <arg2> is the OTP for MySafety24x7 Ripons registration. Enter this OTP to verify mobile number. Thanks Ripons Tech";
    private async sendSMS(message: string, recipients: any[]) {
        try {
            const response = await axios.post(
                VOICENSMS_BASE_URL_SMS,
                {
                    filetype: 1,
                    language: 0,
                    credittype: 7,
                    senderid: "RIPONS",
                    templateid: 0,
                    message: message,
                    ukey: VOICENSMS_AUTHKEY,
                    isrefno: true,
                    msisdnlist: recipients
                },
                {
                    headers: {
                        "content-type": "application/json"
                    },
                    timeout: 30000
                }
            );
            return response.data;
        } catch (error: any) {
            if (error.code === 'ECONNABORTED') {
                logger.error("SMS API timeout:", VOICENSMS_BASE_URL_SMS);
            } else {
                logger.error("Error sending SMS:", error.response?.data || error.message);
            }
            return null;
        }
    }

    async sendOtpSMS(name: string, mobile: string, otp: string) {
        try {
            return await this.sendSMS(this.otpMessage, [{ "phoneno": mobile, "arg1": name, "arg2": otp }]);
        } catch (error) {
            logger.error("sendOtpSMS failed:", error);
            return null;
        }
    }

    async sendMaxOtpSMS(templateId: string, mobile: string) {
        return this.sendSMS(templateId, [
            { mobiles: "91" + mobile }
        ]);
    }

    async sendWelcomeSMS(templateId: string, mobile: string, name: string) {
        return this.sendSMS(templateId, [
            { mobiles: "91" + mobile, NAME: name, NUMBER: mobile, website: "Wintru.in" }
        ]);
    }

    async initiateAutoGeneratedCall(audioFileName: string, mobile: string[]) {
        // logger.log({ audioFileName, mobile });

        try {
            const response = await axios.post(
                VOICENSMS_BASE_URL_CALL,
                {
                    sourcetype: "0",
                    campaigntype: "4",
                    filetype: "2",
                    voicefile: audioFileName,
                    ukey: VOICENSMS_AUTHKEY,
                    serviceno: VOICENSMS_VOICE_SERVICE_NO,
                    ivrtemplateid: "1",
                    retryatmpt: "3",
                    retryduration: "15",
                    msisdn: mobile
                },
                {
                    headers: {
                        "content-type": "application/json"
                    },
                    timeout: 30000
                }
            );
            return response.data;
        } catch (error: any) {
            if (error.code === 'ECONNABORTED') {
                logger.error("SMS API timeout:", VOICENSMS_BASE_URL_CALL);
            } else {
                logger.error("Error sending SMS:", error.response?.data || error.message);
            }
            return null;
        }
    }
}
