import { Router } from "express";
import { ScanController } from "../../controllers/scan.controller";
import { VisitorController } from "../../controllers/visitor.controller";
import { authenticate } from "../../middlewares/auth.middleware";
import { authenticateVisitor } from "../../middlewares/visitorAuth";
import { checkVisitorBlocked } from "../../middlewares/checkVisitorBlocked.middleware";

const router = Router();
const scanController = new ScanController();
const visitorController = new VisitorController();

// Public routes - no authentication required
router.post("/features", scanController.getSubscriptionFeatures);
router.get("/:qrId", scanController.resolveQR);
router.post("/visitor/register", visitorController.registerVisitor);
router.post("/visitor/verify", visitorController.verifyVisitorOTP);




router.get("/apisetu/callback", visitorController.callback);




// Visitor scan (requires visitor token in Authorization header)
router.post("/createRoom", authenticateVisitor, checkVisitorBlocked, scanController.createChatRoomByVisitor);
router.post("/predefinedmsg", authenticateVisitor, checkVisitorBlocked, scanController.getPredefinedMessage);
router.post("/insurance", authenticateVisitor, checkVisitorBlocked, scanController.getVehicleInsurance);
router.post("/initiateAutoGeneratedCall", authenticateVisitor, checkVisitorBlocked, scanController.initiateAutoGeneratedCall);
router.post("/smartcard/details", scanController.getSmartCardDetails);


// Authenticated user scan (no OTP required)
router.post("/createRoomByUser", authenticate, scanController.createChatRoomByUser);
router.post("/predefinedmsgByUser", authenticate, scanController.getPredefinedMessage);
router.post("/insuranceByUser", authenticate, scanController.getVehicleInsurance);

export default router;
